# Generated by Django 5.0.4 on 2024-04-24 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='lecturers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='mainapp.lecturer', verbose_name='Lecturers'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='mainapp.subject', verbose_name='Subjects'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(related_name='faculty', to='mainapp.subject', verbose_name='Subjects'),
        ),
    ]
